// Generated by tmp/generate-student-workbook-source-pages.mjs from local Eureka Math student workbook PDFs.
// Do not edit manually; rerun the generator after source PDF changes.

export const STUDENT_WORKBOOK_SOURCE_PAGES: Record<string, string[]> = {
  "m1-l1": [
    "/source-pages/m1-student/workbook-page-002.png"
  ],
  "m1-l2": [
    "/source-pages/m1-student/workbook-page-006.png"
  ],
  "m1-l3": [
    "/source-pages/m1-student/workbook-page-011.png"
  ],
  "m1-l4": [
    "/source-pages/m1-student/workbook-page-015.png"
  ],
  "m1-l5": [
    "/source-pages/m1-student/workbook-page-019.png"
  ],
  "m1-l6": [
    "/source-pages/m1-student/workbook-page-023.png"
  ],
  "m1-l7": [
    "/source-pages/m1-student/workbook-page-027.png"
  ],
  "m1-l8": [
    "/source-pages/m1-student/workbook-page-031.png"
  ],
  "m1-l9": [
    "/source-pages/m1-student/workbook-page-035.png"
  ],
  "m1-l10": [
    "/source-pages/m1-student/workbook-page-040.png"
  ],
  "m1-l11": [
    "/source-pages/m1-student/workbook-page-044.png"
  ],
  "m1-l12": [
    "/source-pages/m1-student/workbook-page-048.png"
  ],
  "m1-l13": [
    "/source-pages/m1-student/workbook-page-052.png"
  ],
  "m1-l14": [
    "/source-pages/m1-student/workbook-page-056.png"
  ],
  "m1-l15": [
    "/source-pages/m1-student/workbook-page-061.png"
  ],
  "m1-l16": [
    "/source-pages/m1-student/workbook-page-065.png"
  ],
  "m1-l17": [
    "/source-pages/m1-student/workbook-page-069.png"
  ],
  "m1-l18": [
    "/source-pages/m1-student/workbook-page-073.png"
  ],
  "m1-l19": [
    "/source-pages/m1-student/workbook-page-077.png"
  ],
  "m1-l20": [
    "/source-pages/m1-student/workbook-page-081.png"
  ],
  "m1-l21": [
    "/source-pages/m1-student/workbook-page-085.png"
  ],
  "m2-l1": [
    "/source-pages/m2-student/workbook-page-002.png"
  ],
  "m2-l2": [
    "/source-pages/m2-student/workbook-page-006.png"
  ],
  "m2-l3": [
    "/source-pages/m2-student/workbook-page-011.png"
  ],
  "m2-l4": [
    "/source-pages/m2-student/workbook-page-016.png"
  ],
  "m2-l5": [
    "/source-pages/m2-student/workbook-page-021.png"
  ],
  "m2-l6": [
    "/source-pages/m2-student/workbook-page-025.png"
  ],
  "m2-l7": [
    "/source-pages/m2-student/workbook-page-029.png"
  ],
  "m2-l8": [
    "/source-pages/m2-student/workbook-page-033.png"
  ],
  "m2-l9": [
    "/source-pages/m2-student/workbook-page-037.png"
  ],
  "m2-l10": [
    "/source-pages/m2-student/workbook-page-041.png"
  ],
  "m2-l11": [
    "/source-pages/m2-student/workbook-page-045.png"
  ],
  "m2-l12": [
    "/source-pages/m2-student/workbook-page-049.png"
  ],
  "m2-l13": [
    "/source-pages/m2-student/workbook-page-053.png"
  ],
  "m2-l14": [
    "/source-pages/m2-student/workbook-page-057.png"
  ],
  "m2-l15": [
    "/source-pages/m2-student/workbook-page-062.png"
  ],
  "m2-l16": [
    "/source-pages/m2-student/workbook-page-066.png"
  ],
  "m2-l17": [
    "/source-pages/m2-student/workbook-page-070.png"
  ],
  "m2-l18": [
    "/source-pages/m2-student/workbook-page-074.png"
  ],
  "m2-l19": [
    "/source-pages/m2-student/workbook-page-078.png"
  ],
  "m2-l20": [
    "/source-pages/m2-student/workbook-page-082.png"
  ],
  "m2-l21": [
    "/source-pages/m2-student/workbook-page-086.png"
  ],
  "m3-l1": [
    "/source-pages/m3-student/workbook-page-002.png"
  ],
  "m3-l2": [
    "/source-pages/m3-student/workbook-page-006.png"
  ],
  "m3-l3": [
    "/source-pages/m3-student/workbook-page-011.png"
  ],
  "m3-l4": [
    "/source-pages/m3-student/workbook-page-016.png"
  ],
  "m3-l5": [
    "/source-pages/m3-student/workbook-page-020.png"
  ],
  "m3-l6": [
    "/source-pages/m3-student/workbook-page-024.png"
  ],
  "m3-l7": [
    "/source-pages/m3-student/workbook-page-028.png"
  ],
  "m3-l8": [
    "/source-pages/m3-student/workbook-page-032.png"
  ],
  "m3-l9": [
    "/source-pages/m3-student/workbook-page-037.png"
  ],
  "m3-l10": [
    "/source-pages/m3-student/workbook-page-041.png"
  ],
  "m3-l11": [
    "/source-pages/m3-student/workbook-page-046.png"
  ],
  "m3-l12": [
    "/source-pages/m3-student/workbook-page-050.png"
  ],
  "m3-l13": [
    "/source-pages/m3-student/workbook-page-056.png"
  ],
  "m3-l14": [
    "/source-pages/m3-student/workbook-page-061.png"
  ],
  "m3-l15": [
    "/source-pages/m3-student/workbook-page-065.png"
  ],
  "m3-l16": [
    "/source-pages/m3-student/workbook-page-069.png"
  ],
  "m3-l17": [
    "/source-pages/m3-student/workbook-page-073.png"
  ],
  "m3-l18": [
    "/source-pages/m3-student/workbook-page-079.png"
  ],
  "m3-l19": [
    "/source-pages/m3-student/workbook-page-083.png"
  ],
  "m3-l20": [
    "/source-pages/m3-student/workbook-page-087.png"
  ],
  "m3-l21": [
    "/source-pages/m3-student/workbook-page-091.png"
  ],
  "m4-l1": [
    "/source-pages/m4-student/workbook-page-002.png"
  ],
  "m4-l2": [
    "/source-pages/m4-student/workbook-page-006.png"
  ],
  "m4-l3": [
    "/source-pages/m4-student/workbook-page-010.png"
  ],
  "m4-l4": [
    "/source-pages/m4-student/workbook-page-016.png"
  ],
  "m4-l5": [
    "/source-pages/m4-student/workbook-page-020.png"
  ],
  "m4-l6": [
    "/source-pages/m4-student/workbook-page-024.png"
  ],
  "m4-l7": [
    "/source-pages/m4-student/workbook-page-030.png"
  ],
  "m4-l8": [
    "/source-pages/m4-student/workbook-page-035.png"
  ],
  "m4-l9": [
    "/source-pages/m4-student/workbook-page-040.png"
  ],
  "m4-l10": [
    "/source-pages/m4-student/workbook-page-044.png"
  ],
  "m4-l11": [
    "/source-pages/m4-student/workbook-page-049.png"
  ],
  "m4-l12": [
    "/source-pages/m4-student/workbook-page-053.png"
  ],
  "m4-l13": [
    "/source-pages/m4-student/workbook-page-057.png"
  ],
  "m4-l14": [
    "/source-pages/m4-student/workbook-page-062.png"
  ],
  "m4-l15": [
    "/source-pages/m4-student/workbook-page-066.png"
  ],
  "m4-l16": [
    "/source-pages/m4-student/workbook-page-070.png"
  ],
  "m5-l1": [
    "/source-pages/m5-student/workbook-page-002.png"
  ],
  "m5-l2": [
    "/source-pages/m5-student/workbook-page-006.png"
  ],
  "m5-l3": [
    "/source-pages/m5-student/workbook-page-010.png"
  ],
  "m5-l4": [
    "/source-pages/m5-student/workbook-page-013.png"
  ],
  "m5-l5": [
    "/source-pages/m5-student/workbook-page-017.png"
  ],
  "m5-l6": [
    "/source-pages/m5-student/workbook-page-021.png"
  ],
  "m5-l7": [
    "/source-pages/m5-student/workbook-page-025.png"
  ],
  "m5-l8": [
    "/source-pages/m5-student/workbook-page-029.png"
  ],
  "m5-l9": [
    "/source-pages/m5-student/workbook-page-033.png"
  ],
  "m5-l10": [
    "/source-pages/m5-student/workbook-page-037.png"
  ],
  "m5-l11": [
    "/source-pages/m5-student/workbook-page-041.png"
  ],
  "m5-l12": [
    "/source-pages/m5-student/workbook-page-047.png"
  ],
  "m5-l13": [
    "/source-pages/m5-student/workbook-page-052.png"
  ],
  "m5-l14": [
    "/source-pages/m5-student/workbook-page-057.png"
  ],
  "m5-l15": [
    "/source-pages/m5-student/workbook-page-061.png"
  ],
  "m5-l16": [
    "/source-pages/m5-student/workbook-page-065.png"
  ],
  "m5-l17": [
    "/source-pages/m5-student/workbook-page-069.png"
  ],
  "m5-l18": [
    "/source-pages/m5-student/workbook-page-073.png"
  ],
  "m5-l19": [
    "/source-pages/m5-student/workbook-page-077.png"
  ],
  "m5-l20": [
    "/source-pages/m5-student/workbook-page-081.png"
  ],
  "m5-l21": [
    "/source-pages/m5-student/workbook-page-084.png"
  ],
  "m5-l22": [
    "/source-pages/m5-student/workbook-page-088.png"
  ],
  "m5-l23": [
    "/source-pages/m5-student/workbook-page-092.png"
  ],
  "m5-l24": [
    "/source-pages/m5-student/workbook-page-096.png"
  ],
  "m5-l25": [
    "/source-pages/m5-student/workbook-page-098.png"
  ],
  "m5-l26": [
    "/source-pages/m5-student/workbook-page-104.png"
  ],
  "m5-l27": [
    "/source-pages/m5-student/workbook-page-108.png"
  ],
  "m5-l28": [
    "/source-pages/m5-student/workbook-page-112.png"
  ],
  "m5-l29": [
    "/source-pages/m5-student/workbook-page-116.png"
  ],
  "m5-l30": [
    "/source-pages/m5-student/workbook-page-120.png"
  ],
  "m6-l1": [
    "/source-pages/m6-student/workbook-page-002.png"
  ],
  "m6-l2": [
    "/source-pages/m6-student/workbook-page-007.png"
  ],
  "m6-l3": [
    "/source-pages/m6-student/workbook-page-011.png"
  ],
  "m6-l4": [
    "/source-pages/m6-student/workbook-page-019.png"
  ],
  "m6-l5": [
    "/source-pages/m6-student/workbook-page-024.png"
  ],
  "m6-l6": [
    "/source-pages/m6-student/workbook-page-029.png"
  ],
  "m6-l7": [
    "/source-pages/m6-student/workbook-page-034.png"
  ],
  "m6-l8": [
    "/source-pages/m6-student/workbook-page-039.png"
  ],
  "m6-l9": [
    "/source-pages/m6-student/workbook-page-044.png"
  ],
  "m7-l1": [
    "/source-pages/m7-student/workbook-page-002.png"
  ],
  "m7-l2": [
    "/source-pages/m7-student/workbook-page-006.png"
  ],
  "m7-l3": [
    "/source-pages/m7-student/workbook-page-010.png"
  ],
  "m7-l4": [
    "/source-pages/m7-student/workbook-page-016.png"
  ],
  "m7-l5": [
    "/source-pages/m7-student/workbook-page-020.png"
  ],
  "m7-l6": [
    "/source-pages/m7-student/workbook-page-024.png"
  ],
  "m7-l7": [
    "/source-pages/m7-student/workbook-page-028.png"
  ],
  "m7-l8": [
    "/source-pages/m7-student/workbook-page-032.png"
  ],
  "m7-l9": [
    "/source-pages/m7-student/workbook-page-036.png"
  ],
  "m7-l10": [
    "/source-pages/m7-student/workbook-page-040.png"
  ],
  "m7-l11": [
    "/source-pages/m7-student/workbook-page-044.png"
  ],
  "m7-l12": [
    "/source-pages/m7-student/workbook-page-047.png"
  ],
  "m7-l13": [
    "/source-pages/m7-student/workbook-page-052.png"
  ],
  "m7-l14": [
    "/source-pages/m7-student/workbook-page-056.png"
  ],
  "m7-l15": [
    "/source-pages/m7-student/workbook-page-060.png"
  ],
  "m7-l16": [
    "/source-pages/m7-student/workbook-page-064.png"
  ],
  "m7-l17": [
    "/source-pages/m7-student/workbook-page-068.png"
  ],
  "m7-l18": [
    "/source-pages/m7-student/workbook-page-072.png"
  ],
  "m7-l19": [
    "/source-pages/m7-student/workbook-page-077.png"
  ],
  "m7-l20": [
    "/source-pages/m7-student/workbook-page-081.png"
  ],
  "m7-l21": [
    "/source-pages/m7-student/workbook-page-086.png"
  ],
  "m7-l22": [
    "/source-pages/m7-student/workbook-page-092.png"
  ],
  "m7-l23": [
    "/source-pages/m7-student/workbook-page-096.png"
  ],
  "m7-l24": [
    "/source-pages/m7-student/workbook-page-100.png"
  ],
  "m7-l25": [
    "/source-pages/m7-student/workbook-page-104.png"
  ],
  "m7-l26": [
    "/source-pages/m7-student/workbook-page-107.png"
  ],
  "m7-l27": [
    "/source-pages/m7-student/workbook-page-111.png"
  ],
  "m7-l28": [
    "/source-pages/m7-student/workbook-page-117.png"
  ],
  "m7-l29": [
    "/source-pages/m7-student/workbook-page-122.png"
  ],
  "m7-l30": [
    "/source-pages/m7-student/workbook-page-126.png"
  ],
  "m7-l31": [
    "/source-pages/m7-student/workbook-page-131.png"
  ],
  "m7-l32": [
    "/source-pages/m7-student/workbook-page-135.png"
  ],
  "m7-l33": [
    "/source-pages/m7-student/workbook-page-139.png"
  ],
  "m7-l34": [
    "/source-pages/m7-student/workbook-page-141.png"
  ]
};
